---
- hosts: db
  vars:
    db_package: mariadb-server
    db_service: mariadb
    db_users: 
      - db_admin
      - db_user
    config_db_path: /etc/my.cnf

  tasks:
    - name: create db user
      user:
        name: "{{ item }}"
      with_items: "{{ db_users }}"
      when: inventory_hostname in groups['db']

    - name: install db packages
      yum:
        name: "{{ db_package }}"
      when: db_package is defined

    - name: basic database configuration
      include: ex1_configure_database.yml
      vars:
        extra_packages:
          - mariadb-bench
          - mariadb-libs
          - mariadb-test
      when: config_db_path is defined
