---
- hosts: db
  become: yes
  vars:
        db_packages:
          - mariadb-server
          - MySQL-python
        db_service: mariadb
        src_file: 'https://gist.githubusercontent.com/fevangelou/fb72f36bbe333e059b66/raw/899c029e4bd5e81b449588c5638bf8bf9b0ad884/my.cnf'
        dst_file: /etc/my.cnf
  tasks:
    - name: install db_packages
      yum:
        name: "{{ item }}"
      with_items: "{{ db_packages }}"
      notify: start_service

    - name: fetch my.cnf
      get_url:
        url: "{{ src_file }}"
        dest: "{{ dst_file }}"
        owner: mysql
        group: mysql
        seuser: system_u
        setype: mysqld_etc_t
        force: yes
      notify:
        - restart_service
        - set_password

  handlers:
    - name: start_service
      service:
        name: "{{ db_service }}"
        state: started

    - name: restart_service
      service:
        name: "{{ db_service }}"
        state: restarted

    - name: set_password
      mysql_user:
        name: root
        password: redhat

