---
- hosts: all
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: run date command
      command: date
      register: command_result

    - name: debug date
      debug:
        var: command_result.stdout

    - block:
        - name: install web_package
          yum:
            name: "{{ web_package }}"
            state: latest
          failed_when: web_package == 'httpd'
#          ignore_errors: yes

        - name: install db_package
          yum:
            name: "{{ db_package }}"
            state: latest
      rescue:
        - name: install mariadb server
          yum:
            name: "{{ db_package }}"
            state: latest
      always: 
        - name: start mariadb service
          service:
            name: "{{ db_service }}"
            state: started
      when: inventory_hostname in groups['db'] 
