---
# tasks file for myvhost

  - name: install http 
    yum:
      name: httpd
      state: latest

  - name: start http service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: deliver html content
    copy:
      src: html/
      dest: "/var/www/vhost/{{ ansible_hostname }}"
  
  - name: template vhost file
    template:
      src: vhost.conf.j2
      dest: /etc/httpd/conf.d/vhost.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - restart httpd
      

