---
- hosts: all
  user: ansible
  become: true
  tasks:
    - name: copy motd.j2 template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644


