---
- hosts: db
  remote_user: ansible
  become: yes
  vars_files:
     - ex2_secret.yml
  tasks:
    - name: create user
      user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      with_items: "{{ newusers }}"