---
- hosts: web
  become: yes 
  tasks:
    - block:
        - name: include task for install_packages.yml 
          include: install_packages.yml
          vars:
            memory: 256
            web_package: httpd
            ssl_package: mod_ssl
            web_service: httpd

        - name: include task for configure_web.yml
          include: configure_web.yml
          vars:
            https_uri: "https://gist.githubusercontent.com/TheSunMan/4008088/raw/cee9f0fb267c20b69726f00ac6e09979958ec576/httpd.conf%2520Default"
            ssl_uri: "http://www.modssl.org/source/mod_ssl-2.8.30-1.3.39.tar.gz"

        - name: include task for configure_firewall.yml
          include: configure_firewall.yml
          vars:
            fw_package: firewalld
            fw_service: firewalld
          tags: production
      rescue:
        - name: install httpd service
          yum:
            name: httpd
            state: latest
          notify: restart_services

        - name: add debug message
          debug:
            msg: "Failed to import and run all the tasks; installing the web server manually"
      
      always:
        - name: query httpd status
          shell: 
            cmd: systemctl status httpd
  handlers:
        - name: restart_services
          service: 
            name: "{{ item }}"
            state: restarted
          with_items:
            - httpd
            - firewalld

