---
- name: install packages
  yum: 
    name: 
      - "{{ ansible_local.custom.packages.db_package }}"
      - "{{ ansible_local.custom.packages.web_package }}"
    state: latest

- name: start db_service
  service:
    name: "{{ ansible_local.custom.services.db_service }}"
    state: started
    enabled: yes

- name: start web-service
  service:
    name: "{{ ansible_local.custom.services.web_service }}"
    state: started
    enabled: yes
    
